FROM {{ namespace }}/base-tools:{{ tag }}
MAINTAINER {{ maintainer }}

RUN apt-get update \
    && apt-get install -q -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" memcached \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN useradd --user-group memcached \
    && usermod -a -G microservices memcached
